//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechFoodAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiVietGT
    {
        public int MaBVGT { get; set; }
        public string TenBVGT { get; set; }
        public string MoTaBVGT { get; set; }
        public string NoiDungBVGT { get; set; }
        public string HinhAnhBVGT { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
    }
}
