//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechFoodAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiVietBanChay
    {
        public int MaBV { get; set; }
        public string TenBV { get; set; }
        public string MoTaBV { get; set; }
        public string NoiDungBV { get; set; }
        public string HinhAnhBV { get; set; }
        public Nullable<System.DateTime> NgayLapBV { get; set; }
    }
}
