//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechFoodAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiVietHD
    {
        public int MaBVHD { get; set; }
        public string TenBVHD { get; set; }
        public string MoTaBVHD { get; set; }
        public string NoiDungBVHD { get; set; }
        public string HinhAnhBVHD { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
    }
}
