//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechFoodAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaiDat
    {
        public int MaCD { get; set; }
        public string TieuDe { get; set; }
        public string AnhCD { get; set; }
        public string MoTaCD { get; set; }
        public Nullable<System.DateTime> NgayViet { get; set; }
    }
}
