//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechFoodAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuaHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuaHang()
        {
            this.DanhMucDoAns = new HashSet<DanhMucDoAn>();
            this.DSYeuThiches = new HashSet<DSYeuThich>();
            this.ViTienCuaHangs = new HashSet<ViTienCuaHang>();
        }
    
        public int MaCH { get; set; }
        public string TenCH { get; set; }
        public string DiachiCH { get; set; }
        public string DienthoaiCH { get; set; }
        public string MotaCH { get; set; }
        public Nullable<short> DanhGiaCH { get; set; }
        public Nullable<int> MaDonHang { get; set; }
        public Nullable<int> MaKM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMucDoAn> DanhMucDoAns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSYeuThich> DSYeuThiches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViTienCuaHang> ViTienCuaHangs { get; set; }
    }
}
