//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechFoodAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSYeuThich
    {
        public int MaYT { get; set; }
        public string TenYT { get; set; }
        public int MaKH { get; set; }
        public int MaCH { get; set; }
    
        public virtual CuaHang CuaHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
