//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechFoodAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuNVGH
    {
        public int MaLS { get; set; }
        public int MaNV { get; set; }
        public int MaDonHang { get; set; }
        public Nullable<short> TgGiao { get; set; }
        public Nullable<bool> TrangThaiNhanDon { get; set; }
        public Nullable<short> TinhTrangGiaoHang { get; set; }
    
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual NhanVienGiaoHang NhanVienGiaoHang { get; set; }
    }
}
