//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechFoodAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVienGiaoHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVienGiaoHang()
        {
            this.LichSuNVGHs = new HashSet<LichSuNVGH>();
        }
    
        public int MaNV { get; set; }
        public string HoTenNV { get; set; }
        public string TaiKhoanNV { get; set; }
        public string MatKhauNV { get; set; }
        public string EmailNV { get; set; }
        public string DiaChiNV { get; set; }
        public string DienThoaiNV { get; set; }
        public Nullable<System.DateTime> NgaySinhNV { get; set; }
        public string GioiTinh { get; set; }
        public string TrangThaiNV { get; set; }
        public string ViTriHienTai { get; set; }
        public Nullable<int> DiemThuong { get; set; }
        public Nullable<short> DoUuTien { get; set; }
        public Nullable<short> DanhGiaNVGH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuNVGH> LichSuNVGHs { get; set; }
    }
}
